// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type ResponseExtract struct {
	MachineId            int64    `protobuf:"varint,1,opt,name=machineId,proto3" json:"machineId,omitempty"`
	Sequence             uint64   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reserved             int64    `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	IdType               int64    `protobuf:"varint,5,opt,name=idType,proto3" json:"idType,omitempty"`
	Version              int64    `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseExtract) Reset()         { *m = ResponseExtract{} }
func (m *ResponseExtract) String() string { return proto.CompactTextString(m) }
func (*ResponseExtract) ProtoMessage()    {}
func (*ResponseExtract) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *ResponseExtract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseExtract.Unmarshal(m, b)
}
func (m *ResponseExtract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseExtract.Marshal(b, m, deterministic)
}
func (m *ResponseExtract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseExtract.Merge(m, src)
}
func (m *ResponseExtract) XXX_Size() int {
	return xxx_messageInfo_ResponseExtract.Size(m)
}
func (m *ResponseExtract) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseExtract.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseExtract proto.InternalMessageInfo

func (m *ResponseExtract) GetMachineId() int64 {
	if m != nil {
		return m.MachineId
	}
	return 0
}

func (m *ResponseExtract) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ResponseExtract) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ResponseExtract) GetReserved() int64 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ResponseExtract) GetIdType() int64 {
	if m != nil {
		return m.IdType
	}
	return 0
}

func (m *ResponseExtract) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RequestExtract struct {
	Uuid                 uint64   `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestExtract) Reset()         { *m = RequestExtract{} }
func (m *RequestExtract) String() string { return proto.CompactTextString(m) }
func (*RequestExtract) ProtoMessage()    {}
func (*RequestExtract) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *RequestExtract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestExtract.Unmarshal(m, b)
}
func (m *RequestExtract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestExtract.Marshal(b, m, deterministic)
}
func (m *RequestExtract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestExtract.Merge(m, src)
}
func (m *RequestExtract) XXX_Size() int {
	return xxx_messageInfo_RequestExtract.Size(m)
}
func (m *RequestExtract) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestExtract.DiscardUnknown(m)
}

var xxx_messageInfo_RequestExtract proto.InternalMessageInfo

func (m *RequestExtract) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

type ResponseUUID struct {
	Uuid                 uint64   `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUUID) Reset()         { *m = ResponseUUID{} }
func (m *ResponseUUID) String() string { return proto.CompactTextString(m) }
func (*ResponseUUID) ProtoMessage()    {}
func (*ResponseUUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *ResponseUUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUUID.Unmarshal(m, b)
}
func (m *ResponseUUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUUID.Marshal(b, m, deterministic)
}
func (m *ResponseUUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUUID.Merge(m, src)
}
func (m *ResponseUUID) XXX_Size() int {
	return xxx_messageInfo_ResponseUUID.Size(m)
}
func (m *ResponseUUID) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUUID.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUUID proto.InternalMessageInfo

func (m *ResponseUUID) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func init() {
	proto.RegisterType((*Void)(nil), "Void")
	proto.RegisterType((*ResponseExtract)(nil), "ResponseExtract")
	proto.RegisterType((*RequestExtract)(nil), "RequestExtract")
	proto.RegisterType((*ResponseUUID)(nil), "ResponseUUID")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0x9b, 0xce, 0xd8, 0xeb, 0x4f, 0x25, 0x0b, 0x09, 0x83, 0x60, 0x09, 0x2e, 0xba,
	0x90, 0x2c, 0xf4, 0x15, 0x14, 0xe9, 0x36, 0xb6, 0xae, 0xdc, 0x8c, 0x99, 0x0b, 0x06, 0x99, 0x49,
	0xcc, 0xcd, 0x0c, 0xfa, 0x64, 0xbe, 0x9e, 0x4c, 0x74, 0x5a, 0x2a, 0xee, 0xf2, 0xdd, 0x73, 0x7f,
	0x4e, 0x0e, 0xcc, 0x82, 0x37, 0xca, 0x07, 0x17, 0x9d, 0xcc, 0x81, 0x3d, 0x39, 0x5b, 0xcb, 0xaf,
	0x0c, 0xe6, 0x1a, 0xc9, 0xbb, 0x96, 0xf0, 0xfe, 0x23, 0x86, 0xca, 0x44, 0x7e, 0x01, 0xb3, 0xa6,
	0x32, 0xaf, 0xb6, 0xc5, 0x55, 0x2d, 0xb2, 0x45, 0xb6, 0x9c, 0xe8, 0x5d, 0x81, 0x97, 0x70, 0x48,
	0xf8, 0xde, 0x61, 0x6b, 0x50, 0x1c, 0x2c, 0xb2, 0x25, 0xd3, 0x5b, 0x1e, 0x26, 0xa3, 0x6d, 0x90,
	0x62, 0xd5, 0x78, 0x31, 0x49, 0xe2, 0xae, 0x30, 0x4c, 0x06, 0x24, 0x0c, 0x3d, 0xd6, 0x82, 0xa5,
	0xb5, 0x5b, 0xe6, 0xe7, 0x90, 0xdb, 0x7a, 0xfd, 0xe9, 0x51, 0x4c, 0x93, 0xf2, 0x4b, 0x5c, 0x40,
	0xd1, 0x63, 0x20, 0xeb, 0x5a, 0x91, 0x27, 0x61, 0x44, 0x79, 0x05, 0xa7, 0x7a, 0xb8, 0x4b, 0x71,
	0xf4, 0xcd, 0x81, 0x75, 0x9d, 0xfd, 0xb1, 0xcc, 0x74, 0x7a, 0x4b, 0x09, 0xc7, 0xe3, 0xf7, 0x36,
	0x9b, 0xd5, 0xdd, 0x7f, 0x3d, 0x37, 0xcf, 0x70, 0xb4, 0xae, 0xe8, 0xed, 0x11, 0x43, 0x6f, 0x0d,
	0xf2, 0x4b, 0x28, 0x1e, 0x30, 0xa6, 0xee, 0xa9, 0x1a, 0x42, 0x2a, 0x4f, 0xd4, 0xde, 0x8e, 0x6b,
	0x28, 0xc6, 0x93, 0x73, 0xb5, 0xef, 0xa1, 0x3c, 0x53, 0x7f, 0xd2, 0x7c, 0xc9, 0x53, 0xe0, 0xb7,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0x1b, 0x5b, 0x0d, 0x7d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	GetUUID(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ResponseUUID, error)
	Extract(ctx context.Context, in *RequestExtract, opts ...grpc.CallOption) (*ResponseExtract, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetUUID(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ResponseUUID, error) {
	out := new(ResponseUUID)
	err := c.cc.Invoke(ctx, "/TaskService/GetUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Extract(ctx context.Context, in *RequestExtract, opts ...grpc.CallOption) (*ResponseExtract, error) {
	out := new(ResponseExtract)
	err := c.cc.Invoke(ctx, "/TaskService/Extract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	GetUUID(context.Context, *Void) (*ResponseUUID, error)
	Extract(context.Context, *RequestExtract) (*ResponseExtract, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/GetUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetUUID(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestExtract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/Extract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Extract(ctx, req.(*RequestExtract))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUUID",
			Handler:    _TaskService_GetUUID_Handler,
		},
		{
			MethodName: "Extract",
			Handler:    _TaskService_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
